# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4b82a61a06fd7e95020d748a6ee673ff84533f1933192e46a36b64a6d3cbf2bcb91fa6c8d75029ab4b4466b7b3ae12c1e6049d16a5fb1261a8e54df671d9364

test:
  secret_key_base: e9211d060e37c338fe839e0f883d3cb297d6eb02e659ee582962cedfcdc4cd75e7b01965f7d3f0a4c999162cd125ba148f5349255feaa7364a9c775ff333e72a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
